### PR TITLE
fix(credentials): Error handling in OAuth flows

### LINKED ISSUE #557: Clicking cancel in twitter during oauth flow causes a redirect back to the root of the syndesis app
Also I noticed the connectorId is 'null' instead, so unfortunately we lose all context of what the user was doing before starting the oauth flow.

### PR DESCRIPTION
**Pull request by zregvart**
This changes the way credential state cookies are handled so when the
flow is unsuccessful most recent state is considered to contain
providerId (connectorId) and returnUrl. That makes the UI receive proper
callback.

Fixes #557, #464, #509

### CODE REVIEW

File: credential/src/main/java/io/syndesis/credential/CredentialFlowStateHelper.java [hunk 1]
```diff
@@ -16,68 +16,39 @@
...
-    }
-
-    /* default */ static Stream<CredentialFlowState> restoreFrom(
-        final BiFunction<javax.ws.rs.core.Cookie, Class<CredentialFlowState>, CredentialFlowState> restore,
-        final HttpServletRequest request, final HttpServletResponse response) {
+    /* default */ static Set<CredentialFlowState> restoreFrom(final Restorer restore,
+        final HttpServletRequest request) {
         final Cookie[] servletCookies = request.getCookies();
 
         if (servletCookies == null || servletCookies.length == 0) {
```
Comment (jimmidyson) [inline credential/src/main/java/io/syndesis/credential/CredentialFlowStateHelper.java]: Could use `ArrayUtils.isEmpty`

File: credential/src/main/java/io/syndesis/credential/OAuth1CredentialFlowState.java [hunk 2]
```diff
@@ -86,6 +86,10 @@ default Type type() {
     default CredentialFlowState updateFrom(final HttpServletRequest request) {
         final String verifier = request.getParameter("oauth_verifier");
 
+        if (verifier == null || verifier.isEmpty()) {
```
Comment (jimmidyson) [inline credential/src/main/java/io/syndesis/credential/OAuth1CredentialFlowState.java]: Could use `StringUtils.isEmpty`

File: credential/src/main/java/io/syndesis/credential/OAuth2CredentialFlowState.java [hunk 3]
```diff
@@ -90,6 +90,10 @@ default Type type() {
     default CredentialFlowState updateFrom(final HttpServletRequest request) {
         final String code = request.getParameter("code");
 
+        if (code == null || code.isEmpty()) {
```
Comment (jimmidyson) [inline credential/src/main/java/io/syndesis/credential/OAuth2CredentialFlowState.java]: Could use `StringUtils.isEmpty`

**Comment by zregvart** [comment]
Rebased on #574 and incorporated review feedback
